plugins.youtube.enabled=true
plugins.youtube.clients[0]=MUSIC
plugins.youtube.clients[1]=TV
plugins.youtube.clients[2]=ANDROID_VR
plugins.youtube.clients[3]=WEB
plugins.youtube.clients[4]=WEBEMBEDDED
plugins.youtube.oauth.enabled=true
