FROM ghcr.io/lavalink-devs/lavalink:4
COPY lavalink/application.yml /opt/Lavalink/application.yml
ENV SPRING_CONFIG_ADDITIONAL_LOCATION=file:/opt/Lavalink/application.yml
ENV PLUGINS_YOUTUBE_CLIENTS=MUSIC,TV,ANDROID_VR,WEB,WEBEMBEDDED
